//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSW.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AerolineaPai
    {
        public string Id { get; set; }
        public string Pais { get; set; }
        public string AerolineaId { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
    }
}
