//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSW.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string Id { get; set; }
        public string Descripcion { get; set; }
        public int ConsecutivoId { get; set; }
        public int UserId { get; set; }
        public string VueloId { get; set; }
    
        public virtual Consecutivo Consecutivo { get; set; }
        public virtual User User { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
