//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public string Id { get; set; }
        public string NumTarjeta { get; set; }
        public string MesExp { get; set; }
        public string DiaExp { get; set; }
        public string CVV { get; set; }
        public string Monto { get; set; }
        public string Tipo { get; set; }
        public string CompraId { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
