//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoFinalSW_dbEntities1 : DbContext
    {
        public ProyectoFinalSW_dbEntities1()
            : base("name=ProyectoFinalSW_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerolinea> Aerolineas { get; set; }
        public virtual DbSet<AerolineaPai> AerolineaPais { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Consecutivo> Consecutivoes { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Origen> Origens { get; set; }
        public virtual DbSet<PuertaActiva> PuertaActivas { get; set; }
        public virtual DbSet<PuertaAeropuerto> PuertaAeropuertoes { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
    }
}
